### PR TITLE
Changing ModernHttpClient to support .Net 4.5 for shared Windows

### PR DESCRIPTION
**Pull request by kriskats19**

### CODE REVIEW

**Comment by paulcbetts** [comment]
I don't understand this PR at all, why would we do this?

**Comment by kriskats19** [comment]
In our project, we are trying to use ModernHttpClient, but we have to support Android, iOS, and Windows. It makes ModernHttpClient work for the Windows Desktop platform while allowing Native for Android and iOS.

**Comment by nberardi** [comment]
Wouldn't a DI framework easily take care of this situation?

**Comment by kriskats19** [comment]
A DI framework could be one solution, but I feel that others may run into the same situation while using ModernHttpClient in shared projects. The change will not affect iOS or Android implementations. This solution is much more elegant as a "drop in" replacement for System.Net.

**Comment by csunwold** [comment]
ModernHttpClient is a drop in replacement for HttpMessageHandler on platforms that have platform specific libraries that don't have compatible API's. If you want to use an HttpMessageHandler on a Windows system, just use it. HttpMessageHandler is the abstraction, you dont need to pile any more abstraction on top of it.

**Comment by paulcbetts** [comment]
Yeah, I don't think you need to do this, the PLib should shim it in anyways.

**Pull request closed without merging**
