### PR TITLE
Add CachePolicyLevel property on NativeMessageHandler class on iOS to al...

### PR DESCRIPTION
**Pull request by Tableau-David-Potter**
...low the cache policy to be set by the client rather than be hard-coded.

## TODO:

- [x] Implement CachePolicyLevel property
- [x] Replace the CachePolicyLevel property with the EnableCaching property
- [ ] Final testing
- [ ] Done and ready to be pulled

### CODE REVIEW

**Comment by Tableau-David-Potter** [comment]
After a deeper review of the two implementations of cache policy (from Apple and Microsoft), it became apparent that there isn't a one-to-one mapping between them.  As a result, I've changed the implementation to be a simple on-off switch.

**Comment by paulcbetts** [comment]
@Tableau-David-Potter Looks good, thanks! I changed this boolean to `DisableCaching` instead of `EnableCaching`, and also implemented it for Android and PLib

**Comment by Tableau-David-Potter** [comment]
Thanks Paul.

Note that the reason I chose EnableCaching is that the .NET guidelines recommend that you express things in positive terms.  Also something that is kind of weird is the .NET disables caching by default whereas iOS (not sure about Android) enables it by default, so it might make the most sense to disable it by default in this library as well.

**Comment by paulcbetts** [comment]
> Note that the reason I chose EnableCaching is that the .NET guidelines recommend that you express things in positive terms. 

So, the weird thing I wanted to avoid was the fact that this boolean was by default `true` - we want to turn on non-standard behavior, not have standard behavior be on-by-default. I also think that disabling caching should be the *weird* case, not the standard one. 

> Also something that is kind of weird is the .NET disables caching by default whereas iOS (not sure about Android) enables it by default, so it might make the most sense to disable it by default in this library as well.

.NET also disables GZip by default, I think we have plenty of reason in HttpClient to question the original authors' design :)

**Comment by Tableau-David-Potter** [comment]
Yeah, I agree that it is weird that .NET disables caching by default.  Okay, makes sense.

**Comment by alexrainman** [comment]
Maybe this is related or not, but, after using DisableCatching flag in the NativeMessageHandler, we found out that all our JSON responses still go to Library/Caches/<company app identifier>/Cache.db-wal

Can this be fixed?

**Pull request merged**
