### PR TITLE
Add support for portable-net40 profile

### PR DESCRIPTION
**Pull request by stopiccot**
Still needed for some projects that cannot use Profile78

### CODE REVIEW

**Comment by paulcbetts** [comment]
You can definitely maintain this in a fork, but I don't want to add this, sorry

**Comment by stopiccot** [comment]
But how I should use nuget packages with a fork? Publish my own?

**Comment by paulcbetts** [comment]
@stopiccot You could do that, or use something like MyGet

**Comment by stopiccot** [comment]
Isn't it still a good idea for ModernHttpClient to be portable as possible. Look at Newtonsoft.Json - https://github.com/JamesNK/Newtonsoft.Json/tree/master/Src they support everything.

**Comment by stopiccot** [comment]
Can you at least switch to more generic `Profile344`? According to http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview

Profile78 - portable-net45+netcore45+wp8+MonoAndroid1+MonoTouch1
Profile344 - portable-net45+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1

**Comment by paulcbetts** [comment]
Sorry, Profile78 is the one we're centered on. An easy solution for this is to just create your own dummy ModernHttpClient and include it in your PLib build

**Comment by stopiccot** [comment]
Any real reasons to stick to a more limited profile instead of more generic one? Isn't it a whole purpose of portable part to be as portable as it could be? The whole reason why i'm writing to is because we want to get rid of messy custom built patched libs and switch to nice and clean vanilla nuget packages.

**Comment by stopiccot** [comment]
So can you please explain the reason why Profile78 is the only option?

**Comment by stopiccot** [comment]
@paulcbetts so is there any possibility we can come up to something? Cause I really want to migrate our project to nuget packages and I don't want to create garbage ModernHttpClient.Portable package in nuget index. One kitten dies everytime somebody creates garbage packages. And I still don't see any reason we cant make fixes to official repo.

**Comment by Cheesebaron** [comment]
Profile344 includes Silverlight, which also means you are looking at the old way at doing reflection. Whether it is going to affect ModernHttpClient in any way I don't know, what happens when you mix with profiles using the new reflection stuff I don't know either.

My personal opinion is that Silverlight is dead, and should stay dead.

**Comment by paulcbetts** [comment]
> So can you please explain the reason why Profile78 is the only option?

I don't want the maintenance cost and limitation of dealing with ancient profiles. Now later I'll go to add something and it won't be in that old profile.

> Cause I really want to migrate our project to nuget packages and I don't want to create garbage ModernHttpClient.Portable package in nuget index.

I've already given you two ways to not do that, but here's a third - create an Interface that will return you an HttpMessageHandler then inject it as a factory. That way, you can not reference ModernHttpClient in your PLib at all, but still use it in your iOS and Android projects

**Comment by stopiccot** [comment]
> maintenance cost and limitation 
Seriously? For a dummy library with a single file that throws Exceptions?

> I've already given you two ways to not do that, but here's a third
And a forth way to hack instead of fix would be to have patched prebuilt library in git like a have right now. And it's working. So know how to hack it to get it working. But the whole idea is to remove ugly hacks with nice and clean solution.

**Comment by paulcbetts** [comment]
Sorry, I'm not going to argue on this.

**Pull request closed without merging**
